name: Deploy Glue Catalog with Generic Deployer

on:
  repository_dispatch:
    types: [deploy]
    
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout generic deployer
      uses: actions/checkout@v2
      with:
        repository: EPDataMartHR/generic-deployer
        path: generic-deployer
        
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12'

    - uses: aws-actions/setup-sam@v2

    - run: echo "${{ github.event.client_payload.environment }}"
    
    - name: Configure AWS credentials for production
      if: ${{ github.event.client_payload.environment }} == 'pro'
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: arn:aws:iam::${{ secrets.AWS_PROD_ACCOUNT_ID }}:role/${{ secrets.AWS_IAM_ROLE }} -- Sustituir por el nombre del Role
        role-session-name: GitHubActions-Production
        aws-region: ${{ secrets.AWS_REGION }}
        role-duration-seconds: 3600
        audience: sts.amazonaws.com
    - name: Configure AWS credentials for development
      if: ${{ github.event.client_payload.environment }} == 'dev'
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: arn:aws:iam::${{ secrets.AWS_DEV_ACCOUNT_ID }}:role/${{ secrets.AWS_IAM_ROLE }}
        role-session-name: GitHubActions-Development
        aws-region: ${{ secrets.AWS_REGION }}
        role-duration-seconds: 3600
        audience: sts.amazonaws.com

    - name: Run deploy script
      run: |
        cd generic-deployer
        chmod +x deployer.sh
        AWS_REGION=${{ github.event.client_payload.region }} ./deployer.sh ${{ github.event.client_payload.stack_name }} ../cf-glue-catalog/template.yml "${{ github.event.client_payload.environment }}"
